; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
debug_tool = stlink

[env:bluepill_f103c6]
platform = ststm32
board = bluepill_f103c6
framework = arduino
upload_protocol = stlink
debug_tool = stlink

upload_flags = -c set CPUTAPID 0x1ba01477
; az 1-el kezdődő az eredeti, a 2-vel kezdődő a gyengébb klón

monitor_speed = 115200

board_build.f_cpu = 72000000
board_upload.maximum_size = 64512 ; 1024bit a flash végén EEPROM

build_flags =
  ; CAN bus
  -D USE_FULL_LL_DRIVER
  -D HAL_CAN_MODULE_ENABLED 
  
  ;-DHAL_SPI_MODULE_ENABLED

lib_deps =
  pazi88/STM32_CAN @ 1.1.0
  ;khoih-prog/FlashStorage_STM32 @ 1.2.0

lib_extra_dirs =
  D:/UserDocuments/Arduino/modellvasut_src/Library

debug_server =
  C:\.platformio\packages\tool-openocd\bin\openocd.exe
  -s C:\.platformio\packages\tool-openocd\scripts
  -f interface\stlink.cfg
  -c "transport select hla_swd"
  -c "set CPUTAPID 0x1ba01477"
  -f target\stm32f1x.cfg
  -c "reset_config none"